name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    name: version management
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      issues: write
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.1.3
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            conventional-changelog-conventionalcommits
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: store output next version
        id: next_version
        run: |
          echo `git describe --tags --abbrev=0`
