name: Inputs List Workflow

on:
  workflow_call:
    inputs:
      parameter-list:
        type: string
        description: 'parameter list'
        required: true

jobs:
  build:
    name: inputs list
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      issues: write
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: echoing list
        run: |
          VERSION=$( git describe --tags --abbrev=0 )
          echo "::notice::testing list parameters of ${{ inputs.parameter-list }}"
