name: Release Production

on:
  release:
    types: [ created ]

jobs:
  build:
    name: release production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      issues: write
      checks: write
    environment: production
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: echoing something
        run: |
          VERSION=$( git describe --tags --abbrev=0 )
          echo "::notice::Releasing production of ${VERSION}"
